extends SceneTree
## Hidden native scrollbar rails must preserve the content's input paths.

const PlayerFixture = preload("res://tests/godot/player_flow_fixture.gd")
const Quest = preload("res://scripts/talk_quest.gd")
const Style = preload("res://scripts/ui_style.gd")

var checks: int = 0
var failures: int = 0
var _directory: String
var _activations: int = 0
var _gate_overflow_seen: bool = false


func _initialize() -> void:
	_run.call_deferred()


func check(condition: bool, message: String) -> void:
	checks += 1
	if not condition:
		failures += 1
		printerr("FAIL: " + message)


func settle() -> void:
	for frame in range(8):
		await process_frame


func _isolate_quest(node: Node) -> void:
	if node.get_script() == Quest:
		node.save_path = _directory + "/quest.cfg"


func _check_bars(node: Node, context: String) -> void:
	if node is ScrollBar:
		check(not node.is_visible_in_tree(), context + " never displays " + str(node.get_path()))
	for child in node.get_children(true):
		_check_bars(child, context)


func _maximum(scroll: ScrollContainer) -> float:
	var bar := scroll.get_v_scroll_bar()
	return maxf(0.0, bar.max_value - bar.page)


func _record_activation() -> void:
	_activations += 1


func _wheel(point: Vector2) -> void:
	for down in [true, false]:
		var event := InputEventMouseButton.new()
		event.position = point
		event.global_position = point
		event.button_index = MOUSE_BUTTON_WHEEL_DOWN
		event.pressed = down
		root.push_input(event, true)
		await process_frame
	await settle()


func _touch_pointer(point: Vector2, down: bool) -> void:
	# Native ScrollContainer consumes the mouse stream generated by a touchscreen.
	var event := InputEventMouseButton.new()
	event.device = InputEvent.DEVICE_ID_EMULATION
	event.position = point
	event.global_position = point
	event.button_index = MOUSE_BUTTON_LEFT
	event.button_mask = MOUSE_BUTTON_MASK_LEFT if down else 0
	event.pressed = down
	root.push_input(event, true)
	await process_frame


func _check_touch_drag(scroll: ScrollContainer, target: Control, context: String) -> void:
	var clipped := target.get_global_rect().intersection(scroll.get_global_rect())
	check(clipped.has_area(), context + " begins on visible content")
	if not clipped.has_area():
		return
	var point := clipped.get_center()
	var original_hint: bool = Input.emulate_touch_from_mouse
	Input.emulate_touch_from_mouse = true
	check(DisplayServer.is_touchscreen_available(), context + " exposes the native touchscreen path")
	var activations_before := _activations
	await _touch_pointer(point, true)
	# Measure after the press, so focus reveal alone cannot pass the drag check.
	var before: int = scroll.scroll_vertical
	var available: float = _maximum(scroll) - before
	var direction: float = -1.0 if available >= 12.0 else 1.0
	if direction > 0:
		available = before
	var distance: float = minf(72.0 / Style.ui_scale(scroll), maxf(24.0, available))
	check(available >= 12.0, context + " has overflow beyond any initial focus reveal")
	for step in range(1, 7):
		var motion := InputEventMouseMotion.new()
		motion.device = InputEvent.DEVICE_ID_EMULATION
		motion.position = point + Vector2(0, direction * distance * step / 6.0)
		motion.global_position = motion.position
		motion.relative = Vector2(0, direction * distance / 6.0)
		motion.button_mask = MOUSE_BUTTON_MASK_LEFT
		root.push_input(motion, true)
		await process_frame
	check(absf(scroll.scroll_vertical - before) >= minf(10.0, available),
		context + " continuously scrolls after focus settles: before=%d after=%d max=%.1f" % [before, scroll.scroll_vertical, _maximum(scroll)])
	await _touch_pointer(point + Vector2(0, direction * distance), false)
	check(_activations == activations_before, context + " never activates a dragged action")
	# Stop native inertia before the next independent gesture fixture.
	scroll.set_process_internal(false)
	Input.emulate_touch_from_mouse = original_hint
	_check_bars(scroll, context)


func _check_album(quest, context: String) -> void:
	quest._show_album()
	await settle()
	var scroll: ScrollContainer = quest._album_scroll
	var tiles: Array = quest._album_grid.get_children()
	check(tiles.size() == 20 and _maximum(scroll) > 0, context + " exercises the complete overflowing treasure shelf")
	check(scroll.vertical_scroll_mode == ScrollContainer.SCROLL_MODE_SHOW_NEVER,
		context + " hides the album rail while retaining vertical scrolling")
	for item: Control in tiles:
		check(item.focus_mode == Control.FOCUS_ALL, context + " keeps each treasure reachable by keyboard")
	var last: Control = tiles.back()
	scroll.scroll_vertical = 0
	last.grab_focus()
	await settle()
	check(last.has_focus() and scroll.scroll_vertical > 0,
		context + " reaches the final treasure through keyboard focus")
	if last.size.y <= scroll.size.y:
		check(scroll.get_global_rect().grow(1).encloses(last.get_global_rect()),
			context + " fully reveals the final treasure when its tile fits the viewport: scroll_rect=%s tile_rect=%s grid_rect=%s grid_min=%s tile_min=%s scroll=%d max=%.3f page=%.3f columns=%d scale=%.5f" % [
				scroll.get_global_rect(), last.get_global_rect(), quest._album_grid.get_global_rect(),
				quest._album_grid.get_combined_minimum_size(), last.get_combined_minimum_size(),
				scroll.scroll_vertical, _maximum(scroll), scroll.get_v_scroll_bar().page,
				quest._album_grid.columns, Style.ui_scale(quest)])
	var last_label: Label = last.get_meta("label")
	check(scroll.get_global_rect().grow(1).encloses(last_label.get_global_rect()),
		context + " exposes the final treasure's name and collection status")
	root.gui_release_focus()
	scroll.scroll_vertical = 0
	await settle()
	var first: Control = tiles[0]
	var art: Control = first.get_meta("art")
	var art_point := art.get_global_rect().intersection(scroll.get_global_rect()).get_center()
	await _wheel(art_point)
	check(scroll.scroll_vertical > 0, context + " scrolls the hidden album rail with the mouse wheel")
	for key in ["art", "label"]:
		root.gui_release_focus()
		var target: Control = first.get_meta(key)
		var content_rect: Rect2 = quest._album_grid.get_global_transform().affine_inverse() * target.get_global_rect()
		scroll.scroll_vertical = clampi(roundi(content_rect.get_center().y - scroll.size.y * 0.5), 0, floori(_maximum(scroll)))
		await settle()
		await _check_touch_drag(scroll, target, context + " album " + key)
	_check_bars(quest, context + " album")
	quest._show_map()
	await settle()


func _check_gate(app, context: String) -> void:
	app.choose_mode("pop")
	PlayerFixture.choose_pop_player(app)
	await settle()
	var view = app._pop
	view.set_process(false)
	var scroll: ScrollContainer = view._gate
	check(scroll.is_visible_in_tree() and scroll.vertical_scroll_mode == ScrollContainer.SCROLL_MODE_SHOW_NEVER,
		context + " keeps the microphone gate visible with a hidden rail")
	_check_bars(app, context + " microphone gate")
	view.retry_button.pressed.connect(_record_activation)
	view._gate_back.pressed.connect(_record_activation)
	for button: Button in [view.retry_button, view._gate_back]:
		root.gui_release_focus()
		scroll.scroll_vertical = 0
		await settle()
		button.grab_focus()
		await settle()
		check(button.has_focus() and scroll.get_global_rect().grow(1).encloses(button.get_global_rect()),
			context + " reveals the microphone action by keyboard: " + button.text)
		if _maximum(scroll) > 1.0:
			_gate_overflow_seen = true
			await _check_touch_drag(scroll, button, context + " microphone action " + button.text)
			check(view.is_visible_in_tree() and scroll.is_visible_in_tree(),
				context + " keeps the microphone gate open after dragging an action")
	view.retry_button.pressed.disconnect(_record_activation)
	view._gate_back.pressed.disconnect(_record_activation)
	view.set_listening(true, true, "Listening.")
	view._advance_game(view.game.remaining + 1.0)
	await settle()
	check(view.game.phase == "finished" and view._results.is_visible_in_tree(),
		context + " reaches the real Voice Pop result surface")
	_check_bars(app, context + " Voice Pop results")


func _check_surfaces(app, dimensions: Vector2i) -> void:
	root.size = dimensions
	await settle()
	app._layout()
	await settle()
	var context := str(dimensions)
	app.choose_mode("match")
	await settle()
	_check_bars(app, context + " Match")
	app.model.phase = "lost"
	app._refresh()
	await settle()
	_check_bars(app, context + " Match review")
	app.choose_mode("memory")
	await settle()
	_check_bars(app, context + " Memory")
	app._show_collection()
	await settle()
	_check_bars(app, context + " More and room rails")
	for view in ["players", "boards"]:
		app._show_leaderboard(view, false)
		await settle()
		_check_bars(app, context + " " + view)
		app._hide_leaderboard()
	app._hide_collection()
	app.choose_mode("quest")
	await settle()
	_check_bars(app, context + " Talk Quest map")
	app._quest.start_level(1)
	app._quest.set_process(false)
	await settle()
	_check_bars(app, context + " Talk Quest stage")
	await _check_album(app._quest, context)
	await _check_gate(app, context)


func _run() -> void:
	_directory = "user://scrollbar-visibility-%d-%d" % [OS.get_process_id(), Time.get_ticks_usec()]
	check(DirAccess.make_dir_recursive_absolute(_directory) == OK, "Create isolated scrollbar regression saves")
	root.content_scale_mode = Window.CONTENT_SCALE_MODE_CANVAS_ITEMS
	root.content_scale_aspect = Window.CONTENT_SCALE_ASPECT_EXPAND
	root.content_scale_size = Vector2i(480, 480)
	root.size = Vector2i(320, 568)
	var app = load("res://scenes/main.tscn").instantiate()
	app.medal_progress = load("res://scripts/medal_progress.gd").new(_directory + "/medals.cfg", _directory + "/legacy.cfg")
	app.playroom_save_path = _directory + "/room.cfg"
	PlayerFixture.install(app, _directory)
	node_added.connect(_isolate_quest)
	root.add_child(app)
	await settle()
	node_added.disconnect(_isolate_quest)
	app.audio.set_muted(true)
	app.set_reduced_motion(true)
	check(app._quest.save_path == _directory + "/quest.cfg", "Quest uses the isolated save before entering the scene")
	for dimensions in [Vector2i(320, 568), Vector2i(844, 390)]:
		await _check_surfaces(app, dimensions)
	check(_gate_overflow_seen, "The compact viewport exercises actual microphone-gate overflow")
	app.audio.halt()
	app.queue_free()
	await settle()
	for filename: String in DirAccess.get_files_at(_directory):
		check(DirAccess.remove_absolute(_directory.path_join(filename)) == OK, "Remove isolated scrollbar regression save")
	check(DirAccess.remove_absolute(_directory) == OK, "Remove isolated scrollbar regression directory")
	print("Scrollbar visibility: %d checks, %d failures" % [checks, failures])
	quit(1 if failures else 0)
