extends SceneTree
## Hidden native scrollbar rails must preserve the content's input paths.

const PlayerFixture = preload("res://tests/godot/player_flow_fixture.gd")
const Style = preload("res://scripts/ui_style.gd")

var checks: int = 0
var failures: int = 0
var _directory: String
var _activations: int = 0
var _gate_overflow_seen: bool = false


func _initialize() -> void:
	_run.call_deferred()


func check(condition: bool, message: String) -> void:
	checks += 1
	if not condition:
		failures += 1
		printerr("FAIL: " + message)


func settle() -> void:
	for frame in range(8):
		await process_frame


func _check_bars(node: Node, context: String) -> void:
	if node is ScrollBar:
		check(not node.is_visible_in_tree(), context + " never displays " + str(node.get_path()))
	for child in node.get_children(true):
		_check_bars(child, context)


func _maximum(scroll: ScrollContainer) -> float:
	var bar := scroll.get_v_scroll_bar()
	return maxf(0.0, bar.max_value - bar.page)


func _record_activation() -> void:
	_activations += 1


func _touch_pointer(point: Vector2, down: bool) -> void:
	# Native ScrollContainer consumes the mouse stream generated by a touchscreen.
	var event := InputEventMouseButton.new()
	event.device = InputEvent.DEVICE_ID_EMULATION
	event.position = point
	event.global_position = point
	event.button_index = MOUSE_BUTTON_LEFT
	event.button_mask = MOUSE_BUTTON_MASK_LEFT if down else 0
	event.pressed = down
	root.push_input(event, true)
	await process_frame


func _check_touch_drag(scroll: ScrollContainer, target: Control, context: String) -> void:
	var clipped := target.get_global_rect().intersection(scroll.get_global_rect())
	check(clipped.has_area(), context + " begins on visible content")
	if not clipped.has_area():
		return
	var point := clipped.get_center()
	var original_hint: bool = Input.emulate_touch_from_mouse
	Input.emulate_touch_from_mouse = true
	check(DisplayServer.is_touchscreen_available(), context + " exposes the native touchscreen path")
	var activations_before := _activations
	await _touch_pointer(point, true)
	# Measure after the press, so focus reveal alone cannot pass the drag check.
	var before: int = scroll.scroll_vertical
	var available: float = _maximum(scroll) - before
	var direction: float = -1.0 if available >= 12.0 else 1.0
	if direction > 0:
		available = before
	var distance: float = minf(72.0 / Style.ui_scale(scroll), maxf(24.0, available))
	check(available >= 12.0, context + " has overflow beyond any initial focus reveal")
	for step in range(1, 7):
		var motion := InputEventMouseMotion.new()
		motion.device = InputEvent.DEVICE_ID_EMULATION
		motion.position = point + Vector2(0, direction * distance * step / 6.0)
		motion.global_position = motion.position
		motion.relative = Vector2(0, direction * distance / 6.0)
		motion.button_mask = MOUSE_BUTTON_MASK_LEFT
		root.push_input(motion, true)
		await process_frame
	check(absf(scroll.scroll_vertical - before) >= minf(10.0, available),
		context + " continuously scrolls after focus settles: before=%d after=%d max=%.1f" % [before, scroll.scroll_vertical, _maximum(scroll)])
	await _touch_pointer(point + Vector2(0, direction * distance), false)
	check(_activations == activations_before, context + " never activates a dragged action")
	# Stop inertia before the next independent gesture fixture.
	if scroll.has_method("cancel_drag"):
		scroll.call("cancel_drag")
	else:
		scroll.set_process_internal(false)
	Input.emulate_touch_from_mouse = original_hint
	_check_bars(scroll, context)


func _check_gate(app, context: String) -> void:
	app.choose_mode("pop")
	PlayerFixture.choose_pop_player(app)
	await settle()
	var view = app._pop
	view.set_process(false)
	var scroll: ScrollContainer = view._gate
	check(scroll.is_visible_in_tree() and scroll.vertical_scroll_mode == ScrollContainer.SCROLL_MODE_SHOW_NEVER,
		context + " keeps the microphone gate visible with a hidden rail")
	_check_bars(app, context + " microphone gate")
	view.retry_button.pressed.connect(_record_activation)
	view._gate_back.pressed.connect(_record_activation)
	for button: Button in [view.retry_button, view._gate_back]:
		root.gui_release_focus()
		scroll.scroll_vertical = 0
		await settle()
		button.grab_focus()
		await settle()
		check(button.has_focus() and scroll.get_global_rect().grow(1).encloses(button.get_global_rect()),
			context + " reveals the microphone action by keyboard: " + button.text)
		if _maximum(scroll) > 1.0:
			_gate_overflow_seen = true
			await _check_touch_drag(scroll, button, context + " microphone action " + button.text)
			check(view.is_visible_in_tree() and scroll.is_visible_in_tree(),
				context + " keeps the microphone gate open after dragging an action")
	view.retry_button.pressed.disconnect(_record_activation)
	view._gate_back.pressed.disconnect(_record_activation)
	view.set_listening(true, true, "Listening.")
	view._advance_game(view.game.remaining + 1.0)
	await settle()
	check(view.game.phase == "finished" and view._results.is_visible_in_tree(),
		context + " reaches the real Voice Pop result surface")
	_check_bars(app, context + " Voice Pop results")


func _check_surfaces(app, dimensions: Vector2i) -> void:
	root.size = dimensions
	await settle()
	app._layout()
	await settle()
	var context := str(dimensions)
	app.choose_mode("match")
	await settle()
	_check_bars(app, context + " Match")
	app.model.phase = "lost"
	app._refresh()
	await settle()
	_check_bars(app, context + " Match review")
	app.choose_mode("memory")
	await settle()
	_check_bars(app, context + " Memory")
	app._show_collection()
	await settle()
	_check_bars(app, context + " More and room rails")
	for view in ["players", "boards"]:
		app._show_leaderboard(view, false)
		await settle()
		_check_bars(app, context + " " + view)
		app._hide_leaderboard()
	app._hide_collection()
	await _check_gate(app, context)


func _run() -> void:
	_directory = "user://scrollbar-visibility-%d-%d" % [OS.get_process_id(), Time.get_ticks_usec()]
	check(DirAccess.make_dir_recursive_absolute(_directory) == OK, "Create isolated scrollbar regression saves")
	root.content_scale_mode = Window.CONTENT_SCALE_MODE_CANVAS_ITEMS
	root.content_scale_aspect = Window.CONTENT_SCALE_ASPECT_EXPAND
	root.content_scale_size = Vector2i(480, 480)
	root.size = Vector2i(320, 568)
	var app = load("res://scenes/main.tscn").instantiate()
	app.medal_progress = load("res://scripts/medal_progress.gd").new(_directory + "/medals.cfg", _directory + "/legacy.cfg")
	app.playroom_save_path = _directory + "/room.cfg"
	PlayerFixture.install(app, _directory)
	root.add_child(app)
	await settle()
	app.audio.set_muted(true)
	app.set_reduced_motion(true)
	for dimensions in [Vector2i(320, 568), Vector2i(844, 390)]:
		await _check_surfaces(app, dimensions)
	check(_gate_overflow_seen, "The compact viewport exercises actual microphone-gate overflow")
	app.audio.halt()
	app.queue_free()
	await settle()
	for filename: String in DirAccess.get_files_at(_directory):
		check(DirAccess.remove_absolute(_directory.path_join(filename)) == OK, "Remove isolated scrollbar regression save")
	check(DirAccess.remove_absolute(_directory) == OK, "Remove isolated scrollbar regression directory")
	print("Scrollbar visibility: %d checks, %d failures" % [checks, failures])
	quit(1 if failures else 0)
